### ISSUE TITLE
Update deposit status during deposit

### ISSUE THREAD

**Issue by stuartlewis** [DataVault/datavault#126]
During a deposit, the deposit status on the progress bar updates, however the 'status' column at the bottom of the screen doesn't update unless the browser refreshes the screen.

Where this would be most useful is for small deposits which happen so quick the progress bar doesn't display.  In this case the status stays as NOT_STARTED, when it is actually COMPLETE.

**Comment by tomhigginsuom** [comment]
At the moment there is only a small bit of ajax to handle the progress display. We might want to add some kind of data binding so that other aspects of the display can be updated. I think the main problem here is incremental/live updates work with free marker (for example, we built lists of things in free marker and emit static HTML but we really want these things to be updated dynamically).

**Comment by stuartlewis** [comment]
Perhaps another option is to leave the progress bar there, and for it not to disappear at the end?  So if it happens quickly, or if the user has been away from their screen for a while, when they come back the progress bar is still there, and showing complete?

**Comment by tomhigginsuom** [comment]
For now I've made a quick change to simply refresh the page when a completed job is detected (so that at least the status/events/contents are updated).

**Comment by stuartlewis** [comment]
Perfect - seems to do the job just as well.
