### ISSUE TITLE
Vault policy and retention periods

### ISSUE THREAD

**Issue by tomhigginsuom** [DataVault/datavault#168]
At the moment a single "Policy" object can be associated with a vault (in fact a policy is required).

We need to investigate how policies should be described and enforced/monitored - for example, an alerts or notification could be triggered once a retention period is exceeded.

An example retention policy is the EPSRC expectation of 10 years since last access.

**Comment by stuartlewis** [comment]
I might tackle this next - how does the following sound:

Define an AbstractPolicy interface - essentially it has a method along the lines of:  public static Status check(Vault v) which returns a status of OK (keep), REVIEW (check to see if we should keep it), DISPOSE (recommend delete).  This status should probably then be applied to the Vault object, along with the date it was last checked.  A new policy class can then be defined for each of our policies, and it can include code to decide which status the vault is under.

A separate report can then be run from the admin interface to see the status of each vault according to its policy.

A tool should be scriptable, to allow the policies to be checked periodically, perhaps weekly.

**Comment by tomhigginsuom** [comment]
That sounds like a reasonable approach to me. Presumably we would need to look at the individual deposits in the vault - for example, a vault might have a number of deposits over several months/years.

Where do you see these checks being carried out? The broker has access to the DB and also to the metadata directory, so that might be a natural place (either as a periodic job or via new methods in the REST API).

One of the comments at the community meeting was that it would be good for the policies to be explained to the user. Perhaps policies also need a textual "description" that we could display.

________________________________

**Comment by stuartlewis** [comment]
1) Yes.  I assumed that if we pass the vault to the policy engine, it can then access the deposits, (and in the case of EPSRC) the restores, plus metadata etc, in order to make its decision.

2) Good idea - I'll make the policy checks runnable via the broker rest interface.  Any preference for path? /vault/{vaultid}/checkpolicy or something like /policy/vault/{vaultid}/check (or /policy/vault/all/check for all). Or, if we might have other 'jobs' that can be run against vaults, something like /execute/policycheck/{vaultid} (or /execute/checksumcheck/vaultid etc).

3) Good point - maybe the AbstractPolicy also needs a getDescription() method, which contains a hard-coded description of the policy.  Is that batter than keeping the description in the database's policy table?
