### ISSUE TITLE
Improve web front-end

### ISSUE THREAD

**Issue by tomhigginsuom** [DataVault/datavault#25]
The web-front end needs some further development (layout, "beautification" etc.).

Some functionality is available in the API (e.g. list deposit objects, list files). The web front end needs to be extended to call these API methods.

**Comment by robintaylor** [comment]
Some tidy up things that spring to mind...

The webapp currently serves resources using a DefaultServlet, this restricts it to Tomcat as it stands. Is it not possible to find a more generic way, perhaps using <mvc:resources...> ?

In order to use spring:bind in the ftl files I had to declare the spring namespace at the top of each file, why is it not possible to just declare it once in the header file (or somewhere similar)?

Not sure if we are processing forms in the best way 
- review the use of the likes of spring.status.expression
- review the use of passing empty objects to the ftl template.

Review the way we generate URLs for links in the ftl templates. Is springMacroRequestContext.getRequestUri() the best way?

**Comment by tomhigginsuom** [comment]
Here's an example of how the workflow currently looks after the most recent commit: https://github.com/DataVault/datavault/commit/51f66c441da724f20d5625c42dd77bba367ef23b

<img width="1465" alt="1-home-initial" src="https://cloud.githubusercontent.com/assets/11716796/8547323/0de29c20-24b6-11e5-8c19-b8710a2d1e17.png">
<img width="1465" alt="2-create-vault" src="https://cloud.githubusercontent.com/assets/11716796/8547326/0e0e4cb2-24b6-11e5-842b-cd6bbb1e78eb.png">
<img width="1465" alt="3-view-vault" src="https://cloud.githubusercontent.com/assets/11716796/8547325/0e09d31c-24b6-11e5-94d3-15c74d5bfb24.png">
<img width="1465" alt="4-deposit-data" src="https://cloud.githubusercontent.com/assets/11716796/8547329/0e272f98-24b6-11e5-8323-c8bdc91c845c.png">
<img width="1465" alt="5-deposit-view" src="https://cloud.githubusercontent.com/assets/11716796/8547328/0e1e0558-24b6-11e5-903c-8ff530ab411f.png">
<img width="1465" alt="6-deposit-contents" src="https://cloud.githubusercontent.com/assets/11716796/8547327/0e18028e-24b6-11e5-81d8-e0b9c9e8e236.png">
<img width="1465" alt="7-deposit-events" src="https://cloud.githubusercontent.com/assets/11716796/8547324/0dfc6dd0-24b6-11e5-9eca-32952c78fa1e.png">
<img width="1465" alt="8-restore-data" src="https://cloud.githubusercontent.com/assets/11716796/8547330/0e2cab12-24b6-11e5-97b1-77237d32d558.png">
<img width="1465" alt="9-home-multiple-vaults" src="https://cloud.githubusercontent.com/assets/11716796/8547332/0e3500aa-24b6-11e5-845e-d8d28fc2d878.png">
