### ISSUE TITLE
Unit Tests for BagIt Library

### ISSUE THREAD

**Issue by seesmith** [DataVault/datavault#381]
Jira https://www.jira.is.ed.ac.uk/browse/RSS022-67

Unit Tests for BagIt Library to test:

    Manifest includes all files and directories
    Inclusion of Symbolic links
    Empty directories
    Reserved symbols in file and directory names
    Large deposit size
    Large numbers of files in deposit

**Comment by gmh04** [comment]
@seesmith can you expand on what you mean by 'Reserved symbols in file and directory names'?  Also maybe the stress testing should be separated from unit testing - we don't want to have to run a 2 day test each time you do `mvn test`?

**Comment by seesmith** [comment]
@gmh04 good point I will create a separate issue for stress testing.
Filenames need to be able to include spaces and should not be changed from original. Relates to this section of the bagit spec: https://tools.ietf.org/html/draft-kunze-bagit-14#section-7.2.2

**Comment by seesmith** [comment]
If a filename does not match the spec:
https://tools.ietf.org/html/draft-kunze-bagit-14#section-7.2.2 
```
7.2.2.  Windows and Unix file naming

   As specified above, only the Unix-based path separator ('/') may be
   used inside filenames listed in BagIt manifests and "fetch.txt"
   files.  When bags are exchanged between Windows and Unix platforms,
   care should be taken to translate the path separator as needed.
   Receivers of bags on physical media should be prepared for
   filesystems created under either Windows or Unix.  Besides the
   fundamental difference between path separators ('\' and '/'),
   generally, Windows filesystems have more limitations than Unix
   filesystems.  Windows path names have a maximum of 255 characters,
   and none of these characters may be used in a path component:
       < > : " / | ? *
```
Would expect an error to be thrown by BagIt with a useful message. If not the filename should be added to manifest and deposit BagIt as is.

**Comment by robintaylor** [comment]
Hi Claire and George, I commented on this on Slack but was completely on the wrong track, sorry about that. My understanding of this section of the Bagit spec is that it relates to the history of Bagit as a mechanism for transport rather than archive. Files were bundled into a Bag to be sent to another destination not knowing what the receiving operating system might be. In order to avoid problems with filenames the spec *suggests* it might be appropriate to sanitise filenames removing any Unix or Windows specific characters. I think the authors had in mind sending a collection of photos or such like, where the photos rather than the names were the crucial thing. In the case of archive of research data I don't think this should apply. We should be attempting to store the data, including filenames, exactly as given to us. The nature of the data, including filenames, is really not our concern. Cheers.

**Comment by robintaylor** [comment]
Another wee comment - Bagit currently doesn't deal nicely with empty directories. Again this goes back to its root as a transport mechanism, why would you send an empty directory? But for archive purposes we do need to keep empty directories. The problem is that the Bagit spec states that every entry in the manifest should be a filename with a checksum, but empty directories will have no checksum. The easiest thing would be to record the directory name but with no checksum. This might also be the right thing to do for symbolic links. Cheers.
